services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EMO\PaymentStatementParserBundle\:
        resource: '../../*'
        exclude:
            - '../../DependencyInjection/'
            - '../../Model/'
            - '../../*Bundle.php'
