name: Run checks
on:
    - push
    - workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -  uses: actions/checkout@v2
            -  name: Build image 7.2
               run: docker-compose -f docker-compose.yaml build --build-arg PHP_VERSION=7.2 php
            -  name: Check todos
               run: docker-compose -f docker-compose.yaml run php bin/find-todo.sh
            -  name: Run test
               run: docker-compose -f docker-compose.yaml run php vendor/phpunit/phpunit/phpunit
            -  name: Build image 7.3
               run: docker-compose -f docker-compose.yaml build --build-arg PHP_VERSION=7.3 php
            -  name: Check todos
               run: docker-compose -f docker-compose.yaml run php bin/find-todo.sh
            -  name: Run test
               run: docker-compose -f docker-compose.yaml run php vendor/phpunit/phpunit/phpunit
